<?php
declare(strict_types=1);

use PTML\Attr;

return function (Attr $attr): string {
    return match ($attr) {
        Attr::Accept,
        Attr::AcceptCharset,
        Attr::Clazz,
        Attr::Coords,
        Attr::Ping,
        Attr::Style    => 'string|array',
        Attr::Async,
        Attr::Autofocus,
        Attr::Autoplay,
        Attr::Checked,
        Attr::Controls,
        Attr::Default,
        Attr::Defer,
        Attr::Disabled,
        Attr::Download,
        Attr::Formnovalidate,
        Attr::Hidden,
        Attr::Ismap,
        Attr::Loop,
        Attr::Multiple,
        Attr::Muted,
        Attr::Novalidate,
        Attr::Open,
        Attr::Readonly,
        Attr::Required,
        Attr::Reversed,
        Attr::Selected,
        Attr::Wrap     => 'string|bool',
        Attr::Cols,
        Attr::Colspan,
        Attr::Maxlength,
        Attr::Minlength,
        Attr::Rows,
        Attr::Rowspan,
        Attr::Span,
        Attr::Start,
        Attr::Tabindex => 'string|int',
        Attr::Datetime => 'string|\DateTimeInterface',
        Attr::High,
        Attr::Low,
        Attr::Optimum,
        Attr::Size,
        Attr::Step,
        Attr::Width    => 'string|int|float',
        Attr::Max,
        Attr::Min      => 'string|int|float|\DateTimeInterface',
        default        => 'string'
    };
};
